name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version you intend to release (eg x.y.z)

env:
  VERSION: v${{ github.event.inputs.version }}

jobs:
  tag:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version != '' }}
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: 257261
          private_key: ${{ secrets.TOKEN_EXCHANGE_GH_APP_PRIVATE_KEY }}
          repository: ${{ github.repository }}
          permissions: >-
            {"contents": "write"}
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0
      - name: Tag Release
        run: |
          git config --global user.password ${{ steps.generate_token.outputs.token }}
          git tag ${{env.VERSION}}
          git push origin ${{env.VERSION}}
      - name: Slack Notification
        run: |
          jq --null-input '{ text: "vim-buf ${{env.VERSION}} has been released on https://github.com/bufbuild/vim-buf/releases/tag/${{env.VERSION}}" }' \
          | curl -sSL -X POST -H 'Content-Type: application/json' -d @- '${{ secrets.SLACK_RELEASE_NOTIFICATION_WEBHOOK }}'
